name = "2025年广东省湛江市第一中学中考三模历史试题"
province = "广东"
grade = "九年级"
year = "2025"
subject = "历史"
page_id = "3412629365086597120"

[[stemlist]]
origin = ""
stem = "一、单选题"
origin_from_our_bank = []
is_title = true

[[stemlist]]
origin = "24-25七年级上·河南郑州·月考"
stem = "1. 据文献记载，受战乱、环境变化等因素的影响，商朝曾多次迁都。考古发掘也证实，河南郑州商城遗址是商朝早期亳都所在，安阳殷墟是商王盘庚迁徙后的都城遗址。这说明（     ）A．考古发掘的史料更真实可靠B．不同史料导致历史真相难寻C．历史研究需要多重史料印证D．历史认识具有较大的主观性"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2025·广东广州·一模"
stem = "2. 战国时期，“中国”一词的使用频率显著增加，其内涵也变得更加丰富，涵盖了周朝、国都、中原、一统中国等多重意义。这一现象反映的历史发展趋势是（     ）A．制度不断革新B．国家走向统一C．学术渐趋多元D．思想逐渐解放"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2025·湖南·模拟预测"
stem = "3. 汉武帝将盐业经营权重新收归国有，在产盐地设置盐官作为政府的代表，监督盐民进行盐业生产，盐由政府收购、运输和销售。这一举措（     ）A．减轻了农民赋税负担B．改善了国家财政状况C．便利了各地经济交流D．提高了盐铁商人地位"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2025·广东东莞·一模"
stem = "4. 南朝时期，南方一方面承袭原有传统，推广和普及水稻种植；另一方面从北方移植麦、粟、菽等作物。此外，栽桑养蚕、园地栽培、药材种植等行业也渐趋兴旺。材料表明这一时期南方（       ）A．经济结构发生显著变化B．农业发展经济具有单一性C．农业发展已经超过北方D．少数民族开始与汉族交融"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2025·广东湛江·三模"
stem = "5. 北宋孟元老在《东京梦华录》中记载：“市井经纪之家，往往只于市店旋买饮食，不置家蔬。夜市直至三更尽，才五更又复开张。如要闹去处，通晓不绝。”材料说明宋代（     ）A．都市商业贸易兴盛B．城市规划井然有序C．文学艺术成就显著D．经济重心完成南移"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2025·广东湛江·三模"
stem = "6. “以诗证史”是一种史学研究的方法，诗歌不仅反映诗人的个人情感，也映射其所处的时代背景，下表中诗歌与时代背景对应正确的是（     ）选项诗歌时代背景A女为胡妇学胡妆，伎进胡音务胡乐。中外交往频繁B稻米流脂粟米白，公私仓廪俱丰实。开元盛世C暖风熏得游人醉，直把杭州作汴州。北宋的偏安D明月有情还顾我，清风无意不留人。元代的文字狱A．AB．BC．CD．D"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2024·广东湛江·一模"
stem = "7. 下面图示中①和②处填写内容最为恰当的是（     ）    ①    时期政权并立到重建大一统国家城市和国内外贸易空前繁荣：    ②    四大发明技术的成熟A．三国两晋南北朝；实行休养生息政策B．隋唐；郑和下西洋C．辽宋夏金元；经济重心南移完成D．明清；文学艺术硕果累累"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2025·广东深圳·二模"
stem = "8. 郑和下西洋促进了中外友好往来，戚继光抗倭基本解除了中国东南沿海的倭患。万历年间，日本发动侵略朝鲜的战争，明朝应朝鲜请求，两次出兵援助朝鲜，并取得胜利。以上共同体现了明朝（     ）A．中央集权的政治理念B．维护和平的国家意志C．经略海洋的先进观念D．平等互利的外交原则"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2025·广东湛江·三模"
stem = "9. 下面为某同学对《清朝前期统一多民族国家的巩固和发展》这部分内容所做的导图式笔记（部分）。下列选项中对应正确的是（     ）A．甲—澎湖巡检司B．乙—雅克萨之战C．丙—设伊犁将军D．丁—驻藏大臣"
origin_from_our_bank = []
is_title = false
imgs = ["https://img.xkw.com/dksih/QBM/editorImg/2025/6/14/05b1f864-2f08-4bcf-a36b-d097911fa658.png"]

[[stemlist]]
origin = "2025·广东汕头·一模"
stem = "10. 下面这三幅插图最有可能出自（     ）A．《天工开物》B．《资治通鉴》C．《本草纲目》D．《齐民要术》"
origin_from_our_bank = []
is_title = false
imgs = ["https://img.xkw.com/dksih/QBM/editorImg/2025/4/14/2e8f3448-0bdc-431a-b9b9-d74427e267f5.png"]

[[stemlist]]
origin = "2025·广东中山·二模"
stem = "11. 清末爱国人士黄遵宪在给好友的信中写道，“新约规定，天旋地转”……“敲骨吸髓，输此巨款，设机造货，夺我生产”。信中的“新约”（     ）A．开放了中国整个沿海地区B．使清政府成为“洋人的朝廷”C．开始了中国近代化进程D．拓展了列强经济侵略的方式"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2025·广东深圳·二模"
stem = "12. 福州船政局成立后，技术人员和工人按技术高低分别领取不等量的工资，工人的月薪为十多两至二三十两不等，少数技术高超的归国留学人员，月薪高达130余两。可见福州船政局（     ）A．照搬了资本主义雇佣模式B．船舶制造技术实现了近代化C．对技术人才的重视和认可D．管理模式带有浓厚封建色彩"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2025·吉林长春·二模"
stem = "13. 历史学家章开沅曾说：“1895年，中国有3个人各自做出一生最重要的选择：康有为选择了变法，孙中山选择了革命，张謇选择了实业与教育。”这三个人的共同目标是（     ）A．推翻清政府的统治B．实现君主立宪制C．建立民主共和国D．挽救中华民族危亡"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2025·广东·一模"
stem = "14. 下表为20世纪30——40年代国民政府举办的公共展览的部分信息。表中信息反映出这些公共展览的举办旨在（     ）类型内容革命史展览主要有上海文献展览会、广东文物展览会和革命史迹展览会战利品展览在南京、汉口等地开展战利品巡展会、战地资料展览和战地艺术展览出国展览在美国举办“抗战美术展览”、在苏联举办“中国战时绘画展览会”以及在英国举办“中国战时摄影展”A．适应北伐战争需要B．维护一党专政统治C．进行抗战宣传动员D．推动海外贸易发展"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2025·广东湛江·三模"
stem = "15. 辛亥革命后，民众服饰样式纷呈，“西装东装，汉装满装，应有尽有”。中华民国临时政府成立之后，大力推行“剪辫易服”“废止缠足”等法令，传统的婚姻习俗和社交礼仪也发生了改变。这说明，辛亥革命的历史功绩在于（     ）A．推翻了封建专制制度B．推动了国民思想解放C．促进了资本主义发展D．推动了社会生活变革"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2025·广东湛江·三模"
stem = "16. 从晚清到民国，中国的民族资本主义产生了，民族工业在恶劣的生存环境中艰难成长。观察下面民族资本主义发展折线图，对其发展各阶段解读正确的是（     ）A．甲午中日战争后，外国人在华开办工厂，刺激了中国民族工业的产生B．一战期间列强放松对中国的侵略，中国民族工业迎来“短暂的春天”C．20世纪二三十年代，中华民国临时政府颁布法令掀起发展实业热潮D．1937年后，日本发动全面侵华战争，促进了中国民族资本主义发展"
origin_from_our_bank = []
is_title = false
imgs = ["https://img.xkw.com/dksih/QBM/editorImg/2025/6/13/2e7008bb-ba93-4dac-9c64-8bf0b8c8412c.png"]

[[stemlist]]
origin = "2025·广东深圳·二模"
stem = "17. 如图反映了一五计划期间中国工业布局及主要成就，这一工业布局体现了（     ）A．全局导向：兼顾内地与沿海B．市场导向：重点打造外贸产业C．民生导向：大力发展轻工业D．政治导向：交通建设靠近苏联"
origin_from_our_bank = []
is_title = false
imgs = ["https://img.xkw.com/dksih/QBM/editorImg/2025/5/17/f50e8699-eaa6-4c97-ac44-1646b7469963.png"]

[[stemlist]]
origin = "2025·广东湛江·三模"
stem = "18. 先谈判后建交是新中国独特的建交模式。与英国的建交谈判经历曲折。1954年，英国“承认新中国，同蒋介石断绝了外交关系，但在联合国又支持蒋介石，不承认新中国的地位。”周恩来说：“英国只同意我们建交原则的一半，我们就同它建立‘半建交关系’。”即相互建立代办处，不设大使馆。新中国的这一做法（     ）A．使新中国出现第二次建交热潮B．使新中国不至于处于孤立境地C．体现了外交的原则性和灵活性D．体现了中国“求同存异”方针"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2025·山东济南·二模"
stem = "19. 1982年，山东省农业总产值达到154.07亿元，比1978年增长约92%，济南市粮食产量较1978年增长5%，棉花产量增长85%，农村经济向多元化转型。这一变化得益于（     ）A．家庭联产承包责任制的实施B．农村剩余劳动力的大量转移C．城市经济体制改革全面铺开D．建立社会主义市场经济体制"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2025·陕西西安·三模"
stem = "20. 以下是某同学复习时制作的思维导图。据此推断，该同学复习的内容是（     ）A．民族团结与祖国统一B．对外开放格局逐渐形成C．科技文化与社会生活D．中国特色社会主义理论"
origin_from_our_bank = []
is_title = false
imgs = ["https://img.xkw.com/dksih/QBM/2025/5/10/3751859225305088/3753047622582272/STEM/a2d61121ad174d39943105e076260efe.png"]

[[stemlist]]
origin = "2025·广东·一模"
stem = "21. 公元前3世纪至公元2世纪，罗马以罗马城为中心修筑了10万千米的公共大道，20万千米的地方道路，建立起遍及欧洲、北非和中东的道路网络。这满足了当时罗马（     ）A．民主政治的需求B．对外扩张的需求C．城邦经济的要求D．传统文化的要求"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2025·广东深圳·二模"
stem = "22. 马克思指出：“租地农场主成了这种农业工人的实际指挥官，成了他们的剩余劳动的实际剥削者，而土地所有者现在只和这种资本主义租地农场主发生直接关系，而且是单纯的货币关系和契约关系。”对这句话解读正确的是（     ）A．土地所有者租地农场主B．土地所有者农业工人C．租地农场主土地所有权D．租地农场主农业工人"
origin_from_our_bank = []
is_title = false
imgs = ["https://staticzujuan.xkw.com/quesimg/Upload/formula/72559911b4bdd14544b499866d3e0c4a.svg", "https://staticzujuan.xkw.com/quesimg/Upload/formula/72559911b4bdd14544b499866d3e0c4a.svg", "https://staticzujuan.xkw.com/quesimg/Upload/formula/79fb135715cfebddf065edab25e82ccc.svg", "https://staticzujuan.xkw.com/quesimg/Upload/formula/79fb135715cfebddf065edab25e82ccc.svg"]

[[stemlist]]
origin = "2022·江苏南京·一模"
stem = "23. “在当时的科学界和公众之中都引起了巨大反响，宗教领袖和维多利亚王朝都非常震惊，人类和动物的祖先居然是一样的。”材料评述的是（       ）A．《自然哲学的数学原理》B．《共产党宣言》C．《物种起源》D．《战争与和平》"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2025·广东佛山·一模"
stem = "24. 到1850年，英国棉纺织业雇用了制造业中六分之一的劳动力，直接贡献了英国GDP的8%。与这一现象的出现密切相关的是（       ）A．新航路的开辟B．三角贸易C．资产阶级革命D．工业革命"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2025·广东广州·一模"
stem = "25. 下表为19世纪中后期日本、美国、俄国在的部分措施对比。其共同作用是（     ）国家措施日本废除封建身份制度，允许贫民自由择业；取消武士特权，推动阶层流动。美国颁布解放宣言，解放叛乱州奴隶；允许黑人参军，削弱南方经济基础。俄国宣布农奴在法律上获得自由，允许赎买土地，农奴可进城务工。A．废除了贵族特权B．实现了自由平等C．建立了民主政体D．打破了人身依附"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2025·广东湛江·三模"
stem = "26. 1918-1919年，商业广告在苏俄《真理报》上几乎消失。1922年《真理报》中竟然出现了糖业、啤酒、农产品等商业广告，出现这种变化是由于（     ）A．战时共产主义政策实施B．新经济政策的实行C．社会主义工业化的实现D．农业集体化的推动"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2025·山西·一模"
stem = "27. 英国经济学家凯恩斯在评价“凡尔赛—华盛顿体系”时说：“它是一个残忍的胜利者在文明史上所干出的最凶残的行为之一。”这一评价意在说明“凡尔赛—华盛顿体系”（       ）A．根除了帝国主义国家间的矛盾B．是帝国主义国家重新分割世界的体系C．带来了战后世界稳定的新秩序D．使资本主义和社会主义矛盾不断激化"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2025·广东东莞·一模"
stem = "28. 1980年，为了抗议苏联入侵阿富汗，美国等国发起抵制莫斯科奥运会的行动，使得最终只有80个国家参加；1984年，洛杉矶奥运会遭到了苏联、朝鲜、古巴、匈牙利等国的抵制。这说明（     ）A．美苏冷战阻碍了世界文化交流B．国际关系受唯一超级大国的操控C．东西方阵营断绝各领域间联系D．经济全球化遭到美苏等国的抵制"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2025·重庆·一模"
stem = "29. 1960年，有17个非洲国家脱离殖民统治独立，这一年被称为“非洲年”。到60年代末，独立国家已达41个，约占非洲总面积的84%，总人口的88%。这一独立浪潮的发生（     ）A．决定了两极格局的瓦解B．标志所有非洲国家摆脱殖民枷锁C．加速世界殖民体系崩溃D．推动了非暴力不合作运动的进程"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2025·广东深圳·一模"
stem = "30. 近年来，各种AI工具层出不穷，如ChatGPT、DeepSeek等，其以强大的数据分析能力广泛用于互联网搜索、自动化公文处理等。这说明现代世界的基本特点是（     ）A．世界多极化B．经济全球化C．社会信息化D．文化多样化"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = ""
stem = "二、材料题"
origin_from_our_bank = []
is_title = true

[[stemlist]]
origin = "未找到来源"
stem = "31. 瓷器影响世界。阅读材料，回答问题。材料一   目前，在全国发现1000多处宋代的瓷窑，有八大窑系五大名窑之说。据《宋会要样稿》载：“瓷器所出，逾于前代……商贾转贩，舶交海中，远至大食、天竺诸国。”《诸蕃志》亦记：“中国瓷器，为海外诸国所宝，贩光之利，倍于丝绸。”——摘编自《义务教育教科书教师教学用书》（七年级下册）材料二   在16-18世纪时期，通过欧洲人的竞争与参与，当时外瓷光主要有以下几条路线：一条是由葡萄牙人主导，经澳门等地后到里斯本；另一条是西班牙人从墨西哥和南美向亚洲输出大量白银的返程中，携带中国等国家货物运往西班牙的塞维利亚；再一条就是荷兰人和英国人经马六甲海峡、印度，前往中东与欧洲。——摘编自江建新《瓷器改变世界》材料三   瓷器外销曾给国家带来了大量的财政收入……而至清代晚期，欧洲各国、日本、美国出产的瓷器反而大量销往中国内地，严重冲击了中国本土瓷器的市场，一方面，工匠失业或转行，另一方面，由于利润下降，资本投入减少，进一步加剧了行业的萧条状态。——摘编自王光尧《对中国古代输出瓷器的一些认识》等(1)根据材料一，概括宋代瓷器发展的特点，并结合所学知识，分析瓷器贸易兴盛的原因。(2)根据材料二，分析这一时期三条主要外销瓷器路线形成的历史背景。(3)根据材料三并结合所学知识，分析晚清以来中国瓷器贸易衰落的影响。"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = ""
stem = "三、综合题"
origin_from_our_bank = []
is_title = true

[[stemlist]]
origin = "2025·广东湛江·三模"
stem = "32. 阅读材料，完成下列要求。世界现代史大事年表（部分）时间事件1931年9月九一八事变爆发，中华民族抗日战争开始1937年7月日本制造卢沟桥事变1939年9月德国入侵波兰，英、法对德宣战，二战全面爆发1941年12月太平洋战争爆发，美国对日宣战1942年1月美、英、苏、中等26个国家签署《联合国家宣言》，世界反法西斯同盟正式形成1943年12月中、美、英发表《开罗宣言》：日本窃取中国领土，如台湾及其附属岛屿、澎湖群岛等，归还中国1945年8月9日毛泽东发出《对日寇的最后一战》声明1945年9月2日日本正式签署投降书，二战结束1945年10月联合国正式成立，中国成为五个常任理事国之一1955年4月中、印等29个亚非国家和地区代表团参加万隆会议(1)根据材料结合所学知识，标志着中国全民族抗战的开始是哪一事件？(2)阅读材料中的史事，请围绕中华民族抗日战争提炼一个观点，并用材料中的两个史事加以论述。（要求：价值观正确，史实正确，观点明确，史论结合）"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = ""
stem = "四、材料题"
origin_from_our_bank = []
is_title = true

[[stemlist]]
origin = "2025·山西·一模"
stem = "33. 大国之路·历史镜鉴。阅读下列材料，结合所学知识回答问题。材料一   英国和苏联（苏俄）兴衰大事记（部分）·1689年，英国议会通过《权利法案》，为限制王权提供了法律保障。·1763年，英国以胜利者的姿态与法国签定了《巴黎和约》，牢固树立了全球殖民霸权。·1851年，第一届世博会在伦敦召开，宣告英国成为世界上最强大的工业化国家。·1932年，《进口关税法》出台，标志着英国放弃了自由贸易原则，属于不列颠的时代过去了。·1917年11月7日晚，“阿美乐尔”巡洋舰的炮声响起，苏维埃俄国诞生。·1921年，当战时共产主义政策陷入危急之时，列宁制定并着手实施新经济政策。·1940年苏联的工业产值在世界所占比重从1913年的2.6%上升到：10%，跃居欧洲第一，世界第二。·1991年12月25日，苏维埃社会主义共和国联盟解体。材料二   美国崛起于19世纪后半期到20世纪上半期。美国首先集中解决了国内的统一和制度问题，在第二次工业革命中，这个新兴的工业国家以重大科技发明为基础，在19世纪末迅速赶超欧洲强国。通过两次世界大战，美国获得了对欧洲的巨大债券和战争赔偿，实现了世界范围的财富从欧洲向美国的转移。——黄仁伟《大国兴衰的历史比较》材料三   改革开放以来国内生产总值情况改革开放以来城乡居民收入情况表年份城镇居民人均可支配收入（元）农村居民人均可支配收入（元）1978年343.4133.61990年1510.2686.32000年62802253.42017年36396.213432.4(1)根据材料一，对比英国和苏联（苏俄）崛起过程中的异同之处。(2)根据材料二，结合19世纪后半期到20世纪上半期的具体事例，说明美国是如何崛起的。(3)根据材料三并结合所学知识，简述改革开放以来我国经济建设取得巨大成就的主要原因。(4)综上所述，归纳大国崛起的共同因素。"
origin_from_our_bank = []
is_title = false
imgs = ["https://img.xkw.com/dksih/QBM/editorImg/2025/6/13/435ef895-4627-4ad7-97a3-133f57884020.png"]
