name = "2025年福建省厦门市双十中学中考二模历史试题"
province = "福建"
grade = "九年级"
year = "2025"
subject = "历史"
page_id = "3412629399200968704"

[[stemlist]]
origin = ""
stem = "一、单选题"
origin_from_our_bank = []
is_title = true

[[stemlist]]
origin = "2025·福建漳州·二模"
stem = "1. 下图所示文物可用于研究先秦时期的（     ）A．石器制作B．农耕发展C．国家治理D．社会生活"
origin_from_our_bank = []
is_title = false
imgs = ["https://img.xkw.com/dksih/QBM/editorImg/2025/5/23/5d2bf345-0fbf-469f-9597-3072646cab77.png"]

[[stemlist]]
origin = "2022·贵州贵阳·中考真题"
stem = "2. 为保证周初的政治形势，巩固疆土，西周实行“封邦建国，广建诸侯”的政治制度。这一政治制度是（     ）A．禅让制B．世袭制C．分封制D．郡县制"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2025·福建漳州·二模"
stem = "3. “君者，舟也；庶人者，水也。水则载舟，水则覆舟。”此思想（     ）A．延续道家的无为而治B．源自儒家的德政思想C．发展了墨家兼爱主张D．推崇法家的以法治国"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2025·福建厦门·二模"
stem = "4. 汉初研究儒家经典的高级官员仅占5%，到西汉中期这一比例升高到45.1%，导致这一变化的主要政策是（     ）A．铸五铢钱B．盐铁官营C．尊崇儒术D．北击匈奴"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2025·福建厦门·二模"
stem = "5. 秦始皇陵出土的铜马多体矮、颈粗、腿短，而东汉画像石中常见的马的形象则体态健美、四肢健长，带有西域“善马”特征。这一变化主要得益于（     ）A．丝绸之路的开辟B．隋朝大运河的开凿C．文成公主的入藏D．郑和下西洋的推动"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2025·福建厦门·二模"
stem = "6. 如图所示的政治怪象出现在（     ）A．西汉B．东汉C．西晋D．东晋"
origin_from_our_bank = []
is_title = false
imgs = ["https://img.xkw.com/dksih/QBM/2025/6/6/3771397126086656/3774812113895424/STEM/fd0ce9c11d35407dac3ac87536dc8f4b.png"]

[[stemlist]]
origin = "2025·福建厦门·二模"
stem = "7. 《魏书》记载，大臣高闾认为夏商周三代疆域不大却实行封禅（古代帝王在泰山祭告天地的仪式），劝孝文帝也举行封禅大典。孝文帝却认为南方荆州和扬州尚未归顺，不欲封禅。由此可见，孝文帝（     ）A．学习汉族政治制度B．推动北方人口南迁C．加大民族交融力度D．胸怀国家统一大志"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2025·福建厦门·二模"
stem = "8. 唐贞观年间设置“监牧里”作为官府管理耕牛的专门机构。开元十三年，官府养牛达5万头，民间养牛更是不计其数。据此可知，唐朝（     ）A．土地分配制度调整B．官员考核制度完备C．农业生产受到重视D．边境互市交易活跃"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "24-25九年级上·全国·课后作业"
stem = "9. 以图证史是通达史识的一种重要方法。下图（     ）        北宋张择端《清明上河图》（局部）注：图中写有“正店”等字样处，为当时的灯箱广告。A．是研究北宋城市生活的一手史料B．完整再现了北宋社会的繁荣景象C．说明北宋东京城内尚未出现夜市D．应与考古材料印证才有史料价值"
origin_from_our_bank = []
is_title = false
imgs = ["https://img.xkw.com/dksih/QBM/editorImg/2024/9/21/e57cc616-9eb3-4974-a0f6-0eb1af563976.png"]

[[stemlist]]
origin = "2025·福建漳州·二模"
stem = "10. 元朝郭守敬编制的《授时历》，运用中国已有的仪器圭表，融合阿拉伯天文学的传统，精确推算出一年为365.2428天，与现行公历的取值几乎相同。材料旨在说明（     ）A．文明交流推动科技进步B．学习西方符合历史潮流C．社会实践丰富人类生活D．科技发展需要扎根传统"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2025·福建漳州·二模"
stem = "11. 下表列举了白蛇故事中主人公身份的变化，该变化折射出我国古代小说发展的特点是 （     ）时期小说/话本许仙身份唐代《白蛇记》盐铁使之子南宋《西湖三塔记》奚统制（军官）之子明代《白娘子永镇雷锋塔》生药铺主管A．世俗化B．多样化C．自由化D．科学化"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2023·福建·中考真题"
stem = "12. 明末清初，广东的佛山镇以冶铁业发迹，江西的景德镇以陶瓷业扬名，河南的朱仙镇以集商贾繁兴。这表明当时（       ）A．水陆交通发达B．工商业市镇的发展C．商帮资本雄厚D．经济总量居世界首位"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2022·江苏徐州·中考真题"
stem = "13. 下图是清朝前期人口大规模迁移示意图，该现象出现的直接原因是（     ）A．文化专制加强B．民族关系紧张C．市民阶层壮大D．人地矛盾尖锐"
origin_from_our_bank = []
is_title = false
imgs = ["https://img.xkw.com/dksih/QBM/2023/2/21/3179597354582016/3204342548062208/STEM/2029e272c2534fcea64ca987fb5297b7.png"]

[[stemlist]]
origin = "2025·福建厦门·二模"
stem = "14. 清朝大臣张廷玉被皇帝召见，他在辅助皇帝处理政务时，只是抄写传达皇帝的旨意，而不能把自己的意见夹杂进去。张廷玉的职务最有可能是（     ）A．丞相B．太尉C．御史大夫D．军机大臣"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2025·福建漳州·二模"
stem = "15. 福州港开埠通商后，官员设卡收税，严惩与洋人直接茶叶贸易，乡绅呼吁不得卖茶叶给外国人。以致开埠后前十年，英国人未从福州运走茶叶。这一现象表明当时（     ）A．英国势力未深入中国内地B．英国打开中国市场进程受滞C．中国的民族意识全面觉醒D．中国对外贸易实现自主垄断"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2025·福建漳州·二模"
stem = "16. 受第二次工业革命影响，西方列强对华侵略方式转变为资本输出。下列条约内容最符合该特点的是（     ）A．英商进出口纳税、饷费，均宜秉公议定则例B．恩准英国人民，寄居福州、厦门等五处港口C．日本臣民得以在中国任便从事各项工艺制造D．大清国惩办伤害诸国国家及人民之首祸诸臣"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2025·福建厦门·二模"
stem = "17. 《母亲》是一部以辛亥革命为背景的小说，文中描写母亲在革命友人的帮助下忍痛放足，成为一名独立自强的新女性。这一情节折射了辛亥革命（     ）A．提高了中国的国际地位B．促进民族工业发展C．提高了社会的医疗水平D．促进民众思想解放"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2025·福建漳州·二模"
stem = "18. 1918年，陈独秀撰文彻底否定义和团，认为义和团封建迷信、守旧排外；1924年，他又认为义和团具有民族反抗的意义。这一变化反映出历史评价（     ）A．受作者立场影响B．由学者水平决定C．缺乏科学的标准D．被道德准则左右"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2025·福建厦门·二模"
stem = "19. 1935年北平学子发出“华北之大，已经安放不得一张平静的书桌了”的呐喊并掀起了声势浩大的爱国救亡运动。该运动是（     ）A．太平天国运动B．义和团运动C．五四运动D．一二·九运动"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2026九年级·全国·专题练习"
stem = "20. 抗战爆发后，国民党内一部分人认为“中国武器不如人，战必败，再战必亡”；中国共产党内也有少数人对战争的长期性和艰苦性缺乏准确判断和准备。为此，毛泽东发表了（     ）A．《星星之火，可以燎原》B．《论持久战》C．《论联合政府》D．《对日寇的最后一战》"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2025·福建漳州·二模"
stem = "21. “想中央，盼中央，中央来了更遭殃！想老蒋，盼老蒋，老蒋来了米面涨”。这首流传于国统区的民谣体现了（     ）A．民族工业艰难发展B．国民党统治不得人心C．战争时期物资短缺D．民众的参政意愿增强"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2025·福建漳州·二模"
stem = "22. 在过去，欧洲人绘制的世界地图只有欧洲、北非和亚洲；而16世纪初他们绘制的地图中，南美洲的海岸线呈现得较为准确，太平洋第一次被完整纳入。引起这一变化的主要原因是（     ）A．文艺复兴兴起B．新航路的开辟C．民主革命开展D．进化论的提出"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2025·福建漳州·二模"
stem = "23. 有学者认为，法国大革命打开了欧洲人的眼界。在此之前，不管国王做什么都是对的，而经过这场变化，君主统治人民将会更加困难。材料说明法国大革命（     ）A．动摇了欧洲封建制度B．促进了工人运动兴起C．鼓舞殖民地人民斗争D．推动欧洲文化的发展"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2025·福建漳州·二模"
stem = "24. 它在短短八周内点燃了工人自治的火种，尽管“血腥周”终结了这场实验，但它留下的民主参与精神与追求正义的勇气，至今仍在全球革命浪潮中回响。“它”是（     ）A．光荣革命B．巴黎公社C．二月革命D．十月革命"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2025·福建厦门·二模"
stem = "25. 图中的思维导图中，①处应填（     ）A．二月革命B．新经济政策C．罗斯福新政D．马歇尔计划"
origin_from_our_bank = []
is_title = false
imgs = ["https://img.xkw.com/dksih/QBM/editorImg/2025/6/13/760e628c-88c0-4a48-8b13-759f02a5a4b5.png"]

[[stemlist]]
origin = "2025·福建漳州·二模"
stem = "26. 此次两栖作战行动成功后，盟军在西欧的战斗逐渐展开，德国的力量被分散，东线的苏联军队也得到了喘息的机会。“此次两栖作战行动”指的是（     ）A．索姆河战役B．凡尔登战役C．珍珠港事件D．诺曼底登陆"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2025·福建漳州·二模"
stem = "27. 下表说明当时东欧国家（     ）20世纪40-50年代东欧国家经济发展计划名称国家主题第一个五年计划捷克斯洛伐克发展重工业，改变工业结构第一个五年计划阿尔巴尼亚快速地建立社会主义经济基础第一个五年计划罗马尼亚着重发展机器制造工业第一个六年计划波兰实现社会主义工业化A．深受苏联模式的影响B．意图开展军备竞赛C．接受西方“和平演变”D．重视引进高新设备"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2025·福建漳州·二模"
stem = "28. 法德之间一系列历史遗留问题的解决推动了1963年《爱丽舍条约》的签订，从此政治上法国牵头、经济上德国支持的“法德合作”模式开始运行。这有利于（     ）A．瓦解马歇尔计划B．完全摆脱美国的控制C．推动欧洲的联合D．增强欧洲军队战斗力"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = ""
stem = "二、综合题"
origin_from_our_bank = []
is_title = true

[[stemlist]]
origin = "2025·福建厦门·二模"
stem = "29. 水稻种植史是中国农业不断成长、进步的生动写照。材料一时期概况史前目前世界上最早的栽培稻发现于中国，多地发现了距今12000—10000年的栽培稻遗存。距今约7000年，河姆渡人使用以骨耜为主的工具种植水稻。秦汉水稻种植运用了去除杂草、及时灌水排水等技术，并使用草木灰等天然肥料。魏晋南北朝江南地区普遍实行了麦稻兼作，五岭以南地区还种植了双季稻，水稻种植推广了选种育种、施用粪肥、育秧移栽等技术。《齐民要术》记载了水稻种植技术。隋唐发明并推广曲辕犁和筒车等生产工具、曲辕犁轻便灵巧，广泛应用于稻作。宋元水稻一年两熟制、稻麦复种技术得到推广，耕地利用率得到提高。长江中下游广泛使用插秧拔秧工具秧马。明清明代徐光启的著作   A   系统总结了南方稻田的栽培技术。水稻育秧技术也得到了快速发展，形成了多种育秧方法。(1)依据材料一指出A处著作的名称。材料二：唐代以前，水稻在全国粮食生产中不占主要地位。宋代太湖地区的水稻亩产量约450斤，比唐代南方的水稻亩产量增长了60%左右。当时有“苏湖熟，天下足”之说，水稻已经是养活半数中国人的作物。——摘编自曾雄生《中国农业通史》(2)依据材料二，写出宋代水稻种植业的发展情况。材料三20世纪70年代，我国成功培育出籼型杂交水稻，亩产比常规稻增加20%左右。杂交水稻占水稻种植总面积的比例从1976年的0.38%增长到1984年的23%。——依据《中国农业统计资料》等一位同学创作的宣传画(3)依据材料三并结合所学，指出1976—1984年我国水稻总产量的变化趋势，并分析原因。(4)综合以上材料，说明这幅宣传画的含义。"
origin_from_our_bank = []
is_title = false
imgs = ["https://img.xkw.com/dksih/QBM/editorImg/2025/6/14/d145f2c9-3abf-4cee-8b02-094ada0b225f.png", "https://img.xkw.com/dksih/QBM/editorImg/2025/6/14/6d464790-7ead-41fa-bc9d-c4abdbd0b6b2.png", "https://img.xkw.com/dksih/QBM/editorImg/2025/6/14/004bcffb-3f1d-4cc0-a964-3c0fbce84e13.png"]

[[stemlist]]
origin = "2024·北京·中考真题"
stem = "30. 用好红色资源   赓续红色血脉材料一   一位同学参观了中国共产党第一次全国代表大会纪念馆，根据馆中壁画《日出东方》手绘了以下作品。画中红色地标以天安门为中心再现了新民主主义革命时期党的伟大征程。(1)依据材料一，从①至⑤中任选一处红色地标，写出其反映的重大历史事件及其意义。材料二   一位同学参观了中国共产党历史展览馆，以下是他拍摄的部分展品。  ①《中华人民共和国土地改革法》受到广大农民的拥护（照片）②邱少云获授的朝鲜民主主义人民共和国一级国旗勋章③中国第一批解放牌汽车在长春一汽试制成功（照片）④苏州刺绣手工业生产合作社的社员在精绣展品（照片）  ⑤毛泽东听过的“东方红一号”卫星播送的《东方红》乐曲磁带⑥《人民日报》刊登的中共十一届三中全会公报⑦邓小平为深圳经济特区的题词⑧神舟九号航天员穿过的舱内宇航服(2)依据材料二，任选两件展品，说明其反映的史事及其联系。（示例组合除外）示例：⑤⑧⑤我国成功地发射了第一颗人造地球卫星——东方红一号。⑧我国实施载人航天工程，取得了伟大成就。这两项成就都推动了我国航天技术的发展，增强了国防实力，提高了国际地位。材料三   从党的一大会址到党的各个重要革命根据地，从土地革命、抗日战争、解放战争纪念地点到社会主义革命和建设、改革开放重要纪念场所等，每到一地，重温那一段段峥嵘岁月，回顾党一路走过的艰难历程，灵魂都受到一次震撼，精神都受到一次洗礼。每次都是怀着崇敬之心去，带着许多感悟回。——习近平《用好红色资源赓续红色血脉努力创造无愧于历史和人民的新业绩》(3)依据材料三并结合个人对于红色文化资源的参观学习经历，谈谈“用好红色资源，赓续红色血脉”的意义。"
origin_from_our_bank = []
is_title = false
imgs = ["https://img.xkw.com/dksih/QBM/2024/8/21/3566452945444864/3566870367256576/STEM/4b6150aa7dba4a27adf93e6b6616b844.png", "https://img.xkw.com/dksih/QBM/2024/8/21/3566452945444864/3566870367256576/STEM/a689659b185147298deb70d2d3155573.png", "https://img.xkw.com/dksih/QBM/2024/8/21/3566452945444864/3566870367256576/STEM/510c856ae4e74da29561ab6f3382a981.png", "https://img.xkw.com/dksih/QBM/2024/8/21/3566452945444864/3566870367256576/STEM/83ad17fbed624e69a52fe014b09990d7.png", "https://img.xkw.com/dksih/QBM/2024/8/21/3566452945444864/3566870367256576/STEM/062096d037d0485196661272eb7e7702.png", "https://img.xkw.com/dksih/QBM/2024/8/21/3566452945444864/3566870367256576/STEM/f905d73c28ae4f7886625a0db983c2da.png", "https://img.xkw.com/dksih/QBM/2024/8/21/3566452945444864/3566870367256576/STEM/ca11445d9036451383a617219ba2d1d8.png", "https://img.xkw.com/dksih/QBM/2024/8/21/3566452945444864/3566870367256576/STEM/f286669e33f04292af85e7107aa4ec10.png", "https://img.xkw.com/dksih/QBM/2024/8/21/3566452945444864/3566870367256576/STEM/d849a8bd68de4cc3bb3e1ff24980a628.png"]

[[stemlist]]
origin = "2025·福建福州·一模"
stem = "31. 阅读材料，完成下列要求。材料   二战后中外历史大事年表（部分）(1)两极格局最终形成的标志性事件是_______。(2)从材料中提炼出一条二战后世界历史的发展线索，并以此为主题拟定一本历史著作的书名，编写该书的目录结构。（要求：①书名准确体现主题；②目录设置逻辑清晰，体现历史发展脉络；③至少列出两章，每章至少列出材料中的1个史事；④不得照抄示例。）示例书名：《新中国的发展征程》目录第一章   新中国的诞生和向社会主义过渡（选取史事：中华人民共和国成立、三大改造基本完成）第二章   社会主义建设在探索中曲折发展（选取史事：中共八大召开、国民经济调整“八字方针”提出）第三章   改革开放与中国特色社会主义道路（选取史事：中共十一届三中全会召开、中共十四大召开）"
origin_from_our_bank = []
is_title = false
imgs = ["https://img.xkw.com/dksih/QBM/2025/6/6/3771397126086656/3774812114763776/STEM/9b0e2320de9c4b23afb86e9f9cc911f1.png"]
