name = "2026年安徽省亳州市利辛县中考一模历史试题"
name_for_cos = "2026年安徽省亳州市利辛县中考一模历史试题"
province = "安徽"
grade = "九年级"
year = "2026"
subject = "历史"
page_id = "3406737291726880768"

[[stemlist]]
origin = ""
stem = "一、单选题"
origin_from_our_bank = []
is_title = true

[[stemlist]]
origin = "2026·安徽亳州·一模"
stem = "1. 人类文明的源头除了两河流域、尼罗河流域、印度河与恒河流域、黄河与长江流域以及欧洲的爱琴海地区以外，还包括美洲和撒哈拉沙漠以南的非洲。它们各有特点，自成体系，既有个性，又有共性。这说明世界古代文明（     ）A．在交流与碰撞中发展B．呈现多元一体的特点C．全部发源于大河流域D．主要诞生于农耕民族"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2026·安徽亳州·一模"
stem = "2. 《汉谟拉比法典》第199条规定：“如果一个人挖出了一个奴隶的眼睛，或打断了一个奴隶的骨头，他应支付奴隶价值的一半。”这表明法典（     ）A．奠定了欧洲民法的基础B．维护了奴隶主贵族利益C．开创了民主政治的典范D．是两河流域文明的代表"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2026·安徽亳州·一模"
stem = "3. 下图所示地区诞生的人类文明成果包括（     ）①金字塔②0～9计数法③佛教④种姓制度A．①②③B．①②④C．②③④D．①③④"
origin_from_our_bank = []
is_title = false
imgs = ["https://img.xkw.com/dksih/QBM/editorImg/2026/1/2/1af91fe7-aeb3-4827-ac8a-dd7ee6613f27.png?resizew=293"]

[[stemlist]]
origin = "2026·安徽亳州·一模"
stem = "4. 在埃及的亚历山大港，曾存在一个举世闻名的学术中心。来自希腊的学者与埃及的祭司在此共事，他们将希腊的哲学思辨与埃及千年积累的数学、天文学知识相结合，取得了辉煌的成就。这说明（     ）A．希腊民主政治有难以克服的缺陷B．希腊的奴隶制民主政治发展到高峰C．古希腊文明带有明显的海洋色彩D．亚历山大东征促进东西方文化交流"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2023·安徽·二模"
stem = "5. 罗马法所确定的概念、术语，结构严谨，立论清晰，言简意赅，学理精深。这可以表明罗马法（       ）A．是现存第一部完备的成文法典B．一定程度上改善了奴隶的地位C．立法技术已具有相当高的水平D．成为现代各国民法的历史渊源"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "25-26九年级上·天津和平·月考"
stem = "6. 克洛维皈依了基督教，保留了原来罗马大地主的土地，把原属罗马国有的土地和无主土地赐给教会和部下，从而（     ）A．稳固了自己的统治B．开创了法兰克王国C．建立了封君封臣制D．得到教皇为他加冕"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2026·安徽亳州·一模"
stem = "7. 西欧庄园是一个独立的自给自足的单位，它不仅是一种经济组织，还是一种社会组织和政治组织，承担着经济、司法、宗教、政治等方面的职能。据此可知，庄园是（     ）A．中世纪城市的组织形式B．法兰克王国的控制范围C．西欧中世纪社会的基础D．以手工业和商业为中心"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2026·安徽亳州·一模"
stem = "8. 13世纪初，巴黎大学的学生和教师因与当地市政当局发生冲突，集体罢课并威胁迁往其他城市。市政当局最终妥协，同意给予大学更多的司法特权和自治权利。这一事件反映了中世纪大学（     ）A．依赖教会和国王的资助运作B．由教皇直接授予其所有特权C．完全受教会控制而无自治权D．在争取自主权方面的主动性"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2026·安徽亳州·一模"
stem = "9. 日本在律令制时代推行“班田收授法”，其计口授田、课税种类及征收方式，与唐代的均田制、租庸调制高度吻合。这表明（     ）A．鉴真东渡传播中华文化B．日本进入幕府统治时代C．大和政权实现基本统一D．大化改新模仿唐朝律令"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2026·安徽亳州·一模"
stem = "10. 拉伯雷在《巨人传》中构想以“做你愿意做的事”为院规的“德廉美修道院”，并认为人天生有向善的本能。这一文学构思主要体现了对（     ）A．希腊罗马古典文化的复兴B．自然人性之美的赞颂C．东方神秘国度的无限向往D．封建专制制度的批判"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2026·安徽亳州·一模"
stem = "11. 下图航线的开辟者是（     ）A．哥伦布B．迪亚士C．达·伽马D．麦哲伦"
origin_from_our_bank = []
is_title = false
imgs = ["https://img.xkw.com/dksih/QBM/editorImg/2026/1/2/b772ae16-9ee9-4a90-9540-170b54f3796c.png?resizew=325"]

[[stemlist]]
origin = "2026·安徽亳州·一模"
stem = "12. 1701年6月12日英国议会通过的《嗣位法》规定，直接依附于国王的人，不能担任下议院的议员；国王所作的一切决定和政府的命令，必须由同意该项决定的枢密院的成员，即政府的大臣签署才能生效。这说明（     ）A．议会进一步抑制了王权B．国王开始操纵议会事务C．国王的权力得到了加强D．国王与议会的尖锐冲突"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2026·安徽亳州·一模"
stem = "13. 英国官员伯恩比在1759－1760年访问了北美。据他描写，弗吉尼亚人特别“高傲地珍惜自己的自由，忍受不了任何限制，几乎不能容忍任何高高在上的权力的控制，甚至有这种想法他们都受不了。”据此推断，当时弗吉尼亚人（     ）A．拥护斯图亚特王朝统治B．萌生摆脱英国统治的意识C．反对奴隶制种植园经济D．要求加强中央政府的权力"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2026·安徽亳州·一模"
stem = "14. 1793年，路易十六被送上断头台。欧洲一些国家以此为借口，武装干涉法国。这说明（     ）A．攻占巴士底狱宣告法国革命爆发B．雅各宾派实行了革命恐怖政策C．波旁王朝统治触及欧洲各国利益D．法国革命打击了欧洲封建势力"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2026·安徽亳州·一模"
stem = "15. 1761年，英国“奖励工业协会”在飞梭普及导致织布提速后，公开号召发明加快纺纱的机器。这说明（     ）A．纺纱领域急需技术革新B．机器发明依赖科学理论C．机器导致工人大量失业D．生产依赖蒸汽动力升级"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = ""
stem = "二、改错题"
origin_from_our_bank = []
is_title = true

[[stemlist]]
origin = "2026·安徽亳州·一模"
stem = "16. 历史人物通过他们的活动影响历史进程。辨别下列人物解说的正误，并加以改正。（1）图1人物解剖了许多动物，奠定了动物学基础，并且还创立了逻辑学等新的学科。（3）图3人物于1804年加冕称帝。1812年，他率军远征英国，大败而归。（2）图2人物出生于麦加城，他建立了历史上第一个婆罗门教国家。"
origin_from_our_bank = []
is_title = false
imgs = ["https://img.xkw.com/dksih/QBM/2025/12/29/3917152749421568/3917788190564352/STEM/0be80b191f50428bbc655bf3afd66659.png?resizew=147", "https://img.xkw.com/dksih/QBM/2025/12/29/3917152749421568/3917788190564352/STEM/4c68c0a50bc24d5d91b42249912c22c9.png?resizew=153", "https://img.xkw.com/dksih/QBM/2025/12/29/3917152749421568/3917788190564352/STEM/981cb5efe30d4dadac1657add78929a7.png?resizew=113"]

[[stemlist]]
origin = ""
stem = "三、材料题"
origin_from_our_bank = []
is_title = true

[[stemlist]]
origin = "2026·安徽亳州·一模"
stem = "17. 阅读材料，完成下列要求。材料一   14、15世纪，地中海沿岸和大西洋沿岸的某些城市，出现了分散手工工场和集中手工工场。少数富裕的手工业者通过扩大生产规模和细密的生产分工演变为集中的手工工场主。从16世纪开始，原来庄园的管事或大一些的自耕农，从土地所有者——领主那里租来土地和其他生产资料，雇佣农民耕种。然后，再根据契约和领主按一定比例分配全部产品。他们经营的农场成为具有资本主义性质的租地农场。——摘编自部编版《中外历史纲要》（下册）(1)根据材料一，指出欧洲生产领域出现的两种新的经营方式。根据材料一并结合所学知识，概括他们在生产关系上的共同点。材料二   18世纪中期，英国曼彻斯特的纺织业仍以家庭手工作坊为主，纺纱工和织布工多在自家小屋中劳作。至19世纪20年代，随着骡机、动力织布机等设备的推广，大批工人进入集中的工厂，在机器轰鸣声中完成纺织流程。——摘编自克拉潘《现代英国经济史》(2)根据材料二，概括18世纪60年代以来，英国生产领域发生的变化。结合所学知识，分析这一变革首先发生于英国的原因。"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2026·安徽亳州·一模"
stem = "18. 阅读材料，完成下列要求。材料一   马引入美洲后，犁耕开始取代过去的锄耕；原产于非洲东北部的咖啡成为北美日常生活的重要部分，并很快传播开来。玉米进入亚洲，推动了对边远地区的拓荒；美洲的作物比较容易生长，在一定程度上克服了欧、亚、非的农业歉收问题，使很多地区的人口得到快速增长。——摘编自帕特里克·曼宁《世界历史上的移民》(1)根据材料一，概括洲际交流带来的影响。材料二   16—19世纪，横跨大西洋的移民浪潮深刻改变了世界。数百万欧洲移民涌入美洲，寻求土地与机会，建立了新的社会结构。与此同时，超过1200万非洲黑人被作为奴隶强制迁徙到美洲，他们为种植园经济提供了最主要的劳动力，其文化也深刻影响了美洲的社会面貌。这一规模空前的跨洋人口流动，在开发新大陆的同时，也充满了血泪与压迫。——摘编自尼古拉斯·克里斯《五百年跨洋移民史》(2)根据材料二，指出16—19世纪跨大西洋移民的主要构成。根据材料二并结合所学知识，阐释“开发新大陆的同时，也充满了血泪与压迫”。"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = ""
stem = "四、综合题"
origin_from_our_bank = []
is_title = true

[[stemlist]]
origin = "2026·安徽亳州·一模"
stem = "19. 阅读材料，完成下列探究活动。材料   世界历史大事记（部分）时间重大事件1688年英国爆发“光荣革命”1689年英国议会通过《权利法案》，逐渐形成    A    制1776年第二届大陆会议通过《独立宣言》1787年美国宪法依据    B    原则设计了一个联邦制共和国1789年法国大革命爆发，制宪议会通过《人权宣言》1804年《拿破仑法典》颁布实施1848年马克思、恩格斯发表《共产党宣言》1871年建立了世界上第一个无产阶级政权——巴黎公社——据统编版《中国历史》九年级上、下册整理【任务一】梳理史事   完善素材(1)写出表格中A、B处内容。【任务二】制作展板   宣传成果(2)自大事记中任选一项，从历史的角度作简要介绍。【任务三】探究问题   提升认识(3)根据上述材料并结合所学知识，围绕“资本主义发展与社会主义探索”，自拟论题，进行论述。（要求：观点正确，史论结合，表述清晰）"
origin_from_our_bank = []
is_title = false
