name = "2026年北京市西城区中考历史一模考前示范卷"
name_for_cos = "2026年北京市西城区中考历史一模考前示范卷"
province = "北京"
grade = "九年级"
year = "2026"
subject = "历史"
page_id = "3406737157274271744"

[[stemlist]]
origin = ""
stem = "一、单选题"
origin_from_our_bank = []
is_title = true

[[stemlist]]
origin = "23-24七年级上·北京东城·期末"
stem = "1. 下列关于河姆渡人和半坡人生产生活情况表述正确的一项是（       ）序号项目河姆渡人半坡人A地域特点黄河流域，温暖湿润长江中下游地区，雨水充沛B房屋样式C陶器代表人面鱼纹彩陶盆               猪纹陶钵D技术工艺陶纺轮木结构水井A．AB．BC．CD．D"
origin_from_our_bank = []
is_title = false
imgs = ["https://img.xkw.com/dksih/QBM/editorImg/2024/2/1/8cbb9a11-b51f-4e5e-9af6-dc1605471588.jpg?resizew=149", "https://img.xkw.com/dksih/QBM/editorImg/2024/2/1/cf57ac84-1a72-4908-a49c-852f55736111.jpg?resizew=166", "https://img.xkw.com/dksih/QBM/editorImg/2024/2/1/e9309ca9-85eb-45ab-9aa5-915060ba8d75.jpg?resizew=149", "https://img.xkw.com/dksih/QBM/editorImg/2024/2/1/af4c44f5-51ae-4fea-b6e7-faa8cf812445.jpg?resizew=166"]

[[stemlist]]
origin = "2024·北京·三模"
stem = "2. 下列材料共同体现（     ）A．农业发展迅速B．手工业发展迅速C．传统医学成就突出D．文学艺术大放异彩"
origin_from_our_bank = []
is_title = false
imgs = ["https://img.xkw.com/dksih/QBM/editorImg/2025/4/14/50f429bb-1879-45a2-8df0-9bfa59993e30.png?resizew=590"]

[[stemlist]]
origin = "24-25七年级下·北京东城·期中"
stem = "3. 《新全球史》中写道：“尽管此项工程耗资巨大，但是隋炀帝……的投资千年来一直都有回报。它将中国南部与北部的经济融为一体，由此为政治和文化的统一建立了经济基础。”“此项工程”指的是（     ）A．都江堰B．大运河C．赵州桥D．长城"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "24-25七年级下·江西新余·期末"
stem = "4. 某班学生开展中国古代科技成就系列明信片设计活动，已经搜集到部分素材（下侧）还可以推荐的素材有（       ）蔡伦与造纸术张仲景与《伤寒杂病论》祖冲之与圆周率徐光启与《农政全书》①司马迁与《史记》             ②王羲之与《兰亭集序》③毕昇与活字印刷术             ④宋应星与《天工开物》A．①②B．②③C．②④D．③④"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2023·河南周口·一模"
stem = "5. 永乐十四年（1416年），明成祖命郑和等人护送古里、爪哇、满剌加、占城等十余国使者归国；返回时随郑和船队来访的有阿丹国、祖法尔、木骨都束等国使者。这些史事表明郑和下西洋（     ）A．消除了中西方的矛盾B．增进了中外友好往来C．促进了各民族的交融D．解除了东南沿海倭患"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "19-20七年级下·北京东城·期末"
stem = "6. 2020年是故宫建成600周年。1420年明朝北京城基本建成，故宫成为北京城最为雄伟壮丽的建筑，是北京城的核心。故宫的建造，主要体现了A．重视民生B．皇权至上C．中西合璧D．无为而治"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2025·山东日照·一模"
stem = "7. 以下时间轴体现的共同主题是（     ）A．列强侵略的加剧B．中国人民的反抗斗争C．民族资本主义的发展D．社会主义制度的建立"
origin_from_our_bank = []
is_title = false
imgs = ["https://img.xkw.com/dksih/QBM/editorImg/2025/4/19/e9c43d32-f60f-4201-9414-b5a18a588ba8.png?resizew=816"]

[[stemlist]]
origin = "23-24八年级上·北京朝阳·期末"
stem = "8. 20世纪初，他们不再热衷于讨论君主立宪与民主共和孰是孰非，而是转而探究民主社会在中国为什么屡屡失败，于是他们的认识开始深入到思想文化层面。材料中“他们”的代表人物是（     ）A．曾国藩、李鸿章B．康有为、梁启超C．孙中山、黄兴D．陈独秀、鲁迅"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "18-19九年级下·山东日照·月考"
stem = "9. 1937年9月，蒋介石发表庐山谈话，标志着以国共合作为主的抗日民族统一战线正式形成。抗日民族统一战线形成的根本原因是（       ）A．中共制定了正确的方针B．中华民族危机严重C．国民政府对日政策变化D．西安事变的爆发"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "24-25八年级下·北京·期中"
stem = "10. 史论结合是历史学习的一项基本要求。下列关于新中国经济方面的史论，搭配正确的是（     ）史实结论A土地改革消灭了私有制B三大改造社会主义基本制度在我国建立C“一五”计划完全实现了国家工业化D“大跃进”运动遵循了客观的经济规律A．AB．BC．CD．D"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "21-22八年级下·北京朝阳·期末"
stem = "11. 以下示意图反映的是（     ）A．工业生产技术水平提高B．我国经济体制改革不断深化C．对外开放范围逐渐扩大D．农村乡镇企业的出现与发展"
origin_from_our_bank = []
is_title = false
imgs = ["https://img.xkw.com/dksih/QBM/2022/7/8/3018059277590528/3018848613367808/STEM/e735840081f64acb9b1eeeb58a6d3e3c.png?resizew=649"]

[[stemlist]]
origin = "2018·山东青岛·中考真题"
stem = "12. “君士坦丁堡陷落后，当初将古希腊学术保存下来并仔细研读的基督教学者，亲自带着这些珍贵手稿逃到了意大利。他们在此受到热烈欢迎，因为文艺复兴学者正四处搜寻古典文献。”对材料理解正确的是①拜占庭帝国保存了古代希腊文献②拜占庭帝国的灭亡是因为信奉基督教③这些古代希腊文献对文艺复兴的发展起到重要作用④闭关自守导致落后，开放创新促进发展A．②③④B．②④C．①③D．①③④"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2023·北京房山·一模"
stem = "13. 如图，促成东西方贸易路线发生变化的事件是（     ）A．手工工场兴起B．租地农场兴起C．文艺复兴D．新航路开辟"
origin_from_our_bank = []
is_title = false
imgs = ["https://img.xkw.com/dksih/QBM/editorImg/2023/5/8/2773b196-75af-4e2e-880d-14f2a29f2b5f.png?resizew=532"]

[[stemlist]]
origin = "18-19九年级·北京·期中"
stem = "14. 马克思说“1640年革命和1789年革命，并不是英国的革命和法国的革命，这是欧洲范围的革命。他们不是社会中某一阶级对旧制度的胜利，他们产生了欧洲新社会的政治制度……这两次革命不仅反映了他们本身发生的地区的要求，而且在更大程度上反映了整个世界的要求。”这里“整个世界的要求”是指A．争取民族独立B．建立资产阶级统治C．进行技术革新D．进行殖民扩张"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "2021·北京东城·二模"
stem = "15. 二氧化碳是导致全球变暖的主要温室气体之个。观察下图，大气二氧化碳浓度变化的原因应是（     ）大气二氧化碳浓度变化曲线图A．两次工业革命的开展B．两次世界大战的爆发C．经济大危机的爆发D．冷战的发生"
origin_from_our_bank = []
is_title = false
imgs = ["https://img.xkw.com/dksih/QBM/2021/6/3/2735122300641280/2735866000441344/STEM/af9acf9ef5104e44898ce749eb9b4008.png?resizew=275"]

[[stemlist]]
origin = "2024·北京大兴·二模"
stem = "16. 某学习小组开展研究性学习，研究内容有：南美解放者、印度非暴力不合作运动和“非洲年”。其研究的主题是（     ）A．一战后世界新秩序的建立B．两极格局的形成C．亚非拉地区民族独立运动D．经济全球化加强"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = ""
stem = "二、综合题"
origin_from_our_bank = []
is_title = true

[[stemlist]]
origin = "23-24七年级下·北京房山·月考"
stem = "17. 边疆管理材料一① 唐蕃会盟碑②唐王朝为了巩固自己的统治，对边疆民族也采取过武力讨伐的政策，但从总体上讲唐王朝的边疆民族政策是以怀柔、招抚为主。唐王朝对边疆民族采取的和亲政策次数之多、持续时间之长是历代王朝所无法比拟的，先后对吐谷浑、吐蕃、契丹、回纥、突厥、奚、突骑施、南诏等施行了和亲政策，目的在于改善或加强和这些边疆民族的关系。作为以怀柔、招抚为主的边疆民族政策的另一方面则是通过册封来规范和边疆民族的臣属关系。唐王朝也采取了积极开发的政策，其主要内容是发展屯田、开辟互市贸易等。——摘编自马大正《中国古代的边疆政策与边疆治理》③唐朝阎立本《步辇图》，画面描绘了唐太宗接见松赞干布派来的求婚者的场景。(1)写出材料一中①②③的史料类别；概括指出唐朝与边疆各民族进行交往的方式。材料二       元朝不仅版图辽阔，而且对边疆地区实施了长时间和比较稳定的统治，这是前代大一统王朝没有做到的。汉唐王朝疆域辽阔，对内陆边疆地区往往是通过册封和朝贡实施控制，很不稳定。元朝的疆域则与王朝统治相始终，边疆管理也更多地呈现出与内地一体化的趋向。——《中外历史纲要（上）》(2)依据材料二，概括从汉唐到元朝中央政府在边疆管理上的变化，并用史实加以说明。材料三       数千年的中华文明史是在统一观念主导下实现和维护中华民族大融合、大一统的历史，自秦统一后的2200年间，中国统一或基本统一的时间占2/3以上，历史上每一次民族对峙、国家分裂之后，最终的结局仍是民族大融合与新的空前大统一国家的出现。中华文明之所以能够保持发展上的连续性，就在于文化认同与国家统一相辅相成。可以说国家统一的理念是中华民族与生俱来的胎记，是人们普遍的价值取向与理性追求。——《瞭望新闻周刊》(3)依据材料三，指出中国历史发展的主流及其形成的内在因素。"
origin_from_our_bank = []
is_title = false
imgs = ["https://img.xkw.com/dksih/QBM/editorImg/2024/6/25/e6fb7a3a-f26f-4a9d-923c-00d632d2c42b.png?resizew=119", "https://img.xkw.com/dksih/QBM/editorImg/2024/6/25/3462765d-a7ee-4d94-9a47-77afe0778436.png?resizew=287"]

[[stemlist]]
origin = "23-24八年级上·北京顺义·期末"
stem = "18. 某校八年级学生开展了“近代国家出路的探索”研习活动材料一（恭亲王奕䜣等人）希望在不改变中国传统价值观念和基本制度的前提下，通过“采西学”“制洋器”“筹国用”，达到“始则师而法之，继则比而齐之，终则驾而上之”的目标，其“自强”意识为后世所承继，成为中国人“振兴中华”的思想源泉之一。——摘编自杨宏雨《近代以来中国历史转折的三个重大关节点》材料二甲午战败，清廷统治危机进一步加深。先进的中国知识分子开始寻求民族独立、国家富强的新道路。概乎其要，分为两途：一为保全清廷、实行君主立宪的戊戌变法；一为推翻清廷、实行民主共和的辛亥革命。——张研等《清史十五讲》杨椒山祠（公车上书签名地）颐和园仁寿殿（光绪帝在此召见康有为，准其专折奏事）材料三   《新青年》刊登的部分文章刊登时间撰稿人文章及主要内容1915年9月陈独秀《敬告青年》提出新青年六条标准：自主的、进步的、进取的、世界的、实利的、科学的1917年1月胡适《文学改良刍议》主张以白话文作为新文学的语言1918年5月鲁迅《狂人日记》以新文学的形式号召人民推翻“黑漆漆的”吃人社会1919年5月李大钊《我的马克思主义观》对马克思主义做了较为系统的介绍1920年5月陈独秀《上海厚生纱厂湖南女工问题》就女工工资水平、工作时长等问题进行讨论1923年6月瞿秋白翻译《国际歌》，使中国劳动人民和世界无产者得以同声相应(1)依据材料一并结合所学，概括奕䜣等人的主张。写出其践行主张的措施（至少写出两项）。(2)结合所学，写出材料二中两处遗址共同见证的历史事件。分别说出戊戌变法、辛亥革命的历史意义。(3)依据材料三并结合所学，指出《新青年》杂志传播的主要思想及历史作用。"
origin_from_our_bank = []
is_title = false
imgs = ["https://img.xkw.com/dksih/QBM/2024/1/19/3414789624963072/3425020461981696/STEM/5d4d77ac0d684950b7effdb91a88292b.png?resizew=218", "https://img.xkw.com/dksih/QBM/2024/1/19/3414789624963072/3425020461981696/STEM/dee8955e78734f47aab63f11493b8545.png?resizew=240"]

[[stemlist]]
origin = "19-20九年级上·北京西城·期末"
stem = "19. 新航路开辟以来，各地区的联系日益密切，世界发生了巨大的变化。材料一   （1）依据材料一，简要概括新航路开辟后全球交流的主要内容。材料二   今天，金属和塑料补充了石材和木头；①火车、②汽车和③飞机取代了牛、马和驴；④蒸汽机、⑤内燃机代替风力和人力驱动船只；大量合成纤维织物与传统的棉布、毛织品和亚麻织物竞争；⑥电取代了蜡烛，并已成为只需按一下开关便可做许多事的动力之源。——斯塔夫里阿诺斯《全球通史》（2）请将材料二中划线部分的内容按要求填入横线（填序号即可）属于工业革命成果的是        ；属于第二次工业革命成果的是        。材料三   序号资料①19世纪初期，英国出现了工人捣毁机器的反抗运动。②19世纪40年代的曼彻斯特浓烟滚滚，污水横流，方圆几英里寸草不生。③1871年，巴黎的无产阶级和人民群众举行武装起义，推翻了资产阶级的统治，建立了世界上第一个无产阶级政权巴黎公社。④19世纪中叶，英国煤产量占世界总产量的2/3，生铁产量超过世界上其他国家的总和。⑤19世纪以来，百万人口以上的大城市不断出现，1851年，伦敦人口236万，巴黎人口100万以上。⑥1860年，英国伦敦建造了世界上的首条地铁，1897年，波士顿建成美国第一条地铁，并很快使用电气火车；1904年，当时世界上最大的地铁系统在纽约市通车。⑦1892年，德国汉堡因水污染而致霍乱流行，使七千五百余人丧生。⑧1914年，美国福特汽车厂每天能生产汽车近800辆，平均每36秒生产一辆汽车。（3）依据材料三，围绕两次工业革命产生的影响，提炼相关主题。要求：仿照）示例，完成表格示例：材料四   从技术的角度来看，（人类社会发展）决定性的转折是从生命能源（即人力和畜力）为主转向对无生命能源的使用。我们所说的工业革命，其实更好的名字是能源革命。——【英】马丁·沃尔夫《全球化为什么可行》（4）依据材料四中的观点并结合所学，用两次工业革命的相关史实加以说明。材料五   20世纪八九十年代以来，国家之间的经济联系日益紧密，以苹果手机为例，它的各部分零件供应国如图：（5）依据材料五，说明当今世界经济发展的趋势。结合所学，举一例说明这一趋势发展过程中所遭遇的挑战。并谈一谈你对这一趋势及挑战的看法。"
origin_from_our_bank = []
is_title = false
imgs = ["https://img.xkw.com/dksih/QBM/2020/1/9/2373431866015744/2373628628131841/STEM/d51312a4947e446a953e3824678613a6.png?resizew=339", "https://img.xkw.com/dksih/QBM/2020/1/9/2373431866015744/2373628628131841/STEM/907ce56806154088891b15c14d5afce8.png?resizew=486", "https://img.xkw.com/dksih/QBM/2020/1/9/2373431866015744/2373628628131841/STEM/46f3fdd23bed482f92ef6d4ef9299d04.png?resizew=227"]
