name = "浙江省杭州市锦绣育才教育集团2024-2025学年八年级下学期科学期中卷"
province = "浙江"
grade = "八年级"
year = "2024"
subject = "科学"

[[stemlist]]
origin = ""
stem = "一、选择题"
origin_from_our_bank = []
is_title = true

[[stemlist]]
origin = "24-25八年级下·浙江杭州·期中"
stem = "1. 在生活与科研中，我们用符号或模型来表达一定的信息。下列图示不属于符号的（　　）A．s=vtB．C．D．"
origin_from_our_bank = []
is_title = false
imgs = [
    "https://img.xkw.com/dksih/QBM/editorImg/2025/6/3/5e24e267-5a8a-408c-a031-a851fbd1e84a.png",
    "https://img.xkw.com/dksih/QBM/editorImg/2025/6/3/2fb551a1-d9d1-4161-b8f2-d508ef7b66df.png",
    "https://img.xkw.com/dksih/QBM/editorImg/2025/6/3/56866722-2352-45ac-9b90-ca97d3938b96.png",
]

[[stemlist]]
origin = "24-25八年级下·浙江杭州·期中"
stem = "2. 学会分类是我们生活常用的一种技能，下列选项符合如图所示关系的是（　　）选项abcA混合物冰水混合物水B纯净物化合物金刚石C单质金属汞D纯净物单质冰A．AB．BC．CD．D"
origin_from_our_bank = []
is_title = false
imgs = ["https://img.xkw.com/dksih/QBM/editorImg/2025/5/28/13d7dc4d-9fed-4f93-80d9-31968090544d.png"]

[[stemlist]]
origin = "24-25八年级下·浙江杭州·期中"
stem = "3. 推理是一种重要的科学思维方法。以下推理结果正确的是（　　）A．分子、原子都是构成物质的微粒，因此物质一定都是由分子或原子构成的B．质子数决定元素种类，因此同种元素质子数一定相同C．单质只含一种元素，因此含一种元素的物质一定是单质D．化合物是由不同种元素组成的纯净物，因此不同种元素组成物质一定是化合物"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "24-25八年级下·浙江杭州·期中"
stem = "4. 某物质化学式HnXO2n+1，则X的化合价为（　　）A．+（2n-1）B．+2nC．+（n+1）D．+（3n+2）"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "24-25八年级下·浙江杭州·期中"
stem = "5. 疫情期间，政府提倡要勤消毒，该消毒剂可表示为RO2。实验测得该氧化物R与O的质量比为71:64，则RO2的化学式为（　　）A．CO2B．ClO2C．NO2D．SO2"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "22-23八年级下·浙江衢州·期末"
stem = "6. 小科有三个N极和一个S极被涂黑的小磁针，将它们摆在条形磁铁周围，现象如图所示，其中S被涂黑的小磁针是（　　）A．甲B．乙C．丙D．丁"
origin_from_our_bank = []
is_title = false
imgs = ["https://img.xkw.com/dksih/QBM/editorImg/2024/9/11/eca07d6d-7472-4fd4-aad5-0de78f358fa4.png"]

[[stemlist]]
origin = "24-25八年级下·浙江杭州·期中"
stem = "7. 如图是一款家用充电式电动螺丝刀，该电动螺丝刀在工作过程中能够通过正转和反转来实现紧螺丝或松螺丝的双重功能，下面四幅图中与这种电动螺丝刀的工作原理相同的是（　　）A．B．C．D．"
origin_from_our_bank = []
is_title = false
imgs = [
    "https://img.xkw.com/dksih/QBM/editorImg/2025/6/4/cb85764c-4ab3-4fac-8647-0da1a99dc066.jpg",
    "https://img.xkw.com/dksih/QBM/editorImg/2025/6/4/8908086f-5e56-4bf5-9313-7be0cd7ac281.png",
    "https://img.xkw.com/dksih/QBM/editorImg/2025/6/4/a0a43312-de97-418b-bf75-0087fdb6b748.png",
    "https://img.xkw.com/dksih/QBM/editorImg/2025/6/4/851d8848-8738-4636-8a5c-29844babe98f.png",
    "https://img.xkw.com/dksih/QBM/editorImg/2025/6/4/720d08b1-f56e-44ac-875d-820194f1c444.png",
]

[[stemlist]]
origin = "24-25八年级下·浙江杭州·期中"
stem = "8. 患流感发高烧时，医学上常使用布洛芬来退烧，主要成分其化学式为C13H18O2,下列关于布洛芬的叙述中正确的是（　　）A．碳元素质量分数最大B．相对分子质量是206克C．C、H、O三种元素组成的混合物D．C13H18O2分子由13个碳原子，18个氢原子和2个氧原子构成"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "24-25八年级下·浙江杭州·期中"
stem = "9. 一种原子的核内有8个质子和8个中子，另一种原子的核内有8个质子和10个中子，则下列说法不正确的是（　　）A．它们互为同位素原子B．它们的质量相同C．它们同属于一种元素D．它们具有相同的核外电子数"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "24-25八年级下·浙江杭州·期中"
stem = "10. 如图天平右盘中“▲”为一个C-12原子质量的，据图推测A原子的相对原子质量是（　　）A．B．18C．12D．9"
origin_from_our_bank = []
is_title = false
imgs = [
    "https://staticzujuan.xkw.com/quesimg/Upload/formula/b624e6d456c5aa077dfd00ada3a311d4.svg",
    "https://img.xkw.com/dksih/QBM/editorImg/2025/6/4/55f2c7ad-dda0-48b4-86f5-3d5b69e5324a.png",
    "https://staticzujuan.xkw.com/quesimg/Upload/formula/f558992e649b93ee36f37513781311a8.svg",
]

[[stemlist]]
origin = "18-19九年级下·浙江台州·期中"
stem = "11. 如图所示，盛水烧杯放置在电磁铁的A端上，烧杯中水面上漂浮着一个空心铁球。当电磁铁磁性的强弱发生改变时，烧杯中的空心铁球会上下浮动。现闭合开关S后，将滑动变阻器的滑片P向左滑动。针对这种情况，下列说法中正确的是（       ）A．电磁铁A端为S极，烧杯中水面上升B．电磁铁A端为S极，烧杯中水面下降C．电磁铁A端为N极，烧杯中水面上升D．电磁铁A端为N极，烧杯中水面下降"
origin_from_our_bank = []
is_title = false
imgs = ["https://img.xkw.com/dksih/QBM/2019/4/28/2192208203177984/2238400675643392/STEM/dd946570c90f4948956524358cd35f9d.png"]

[[stemlist]]
origin = "24-25八年级下·浙江杭州·期中"
stem = "12. SO3和X的混合气体中，氧元素的质量分数为52%，则X是下列气体中的（　　）A．CO2B．NO2C．COD．SO2"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "23-24八年级下·浙江杭州·阶段练习"
stem = "13. 燃气安全检查过程中，技术人员在某住户家中用测电笔测试金属燃气管道，发现：闭合厨房开关S、灯L亮，测电笔氖管发光；断开厨房开关S、灯L熄灭，测电笔氖管不发光。该住户家中，厨房照明电路的导线绝缘皮破损处与管道接触的实际情况是（       ）A．B．C．D．"
origin_from_our_bank = []
is_title = false
imgs = [
    "https://img.xkw.com/dksih/QBM/editorImg/2025/3/5/414af21a-31fc-4111-91f0-4d59f52fcc66.png",
    "https://img.xkw.com/dksih/QBM/editorImg/2025/3/5/60140a4b-20a2-4bd7-a248-edd29992549f.png",
    "https://img.xkw.com/dksih/QBM/editorImg/2025/3/5/10ef83e8-cde3-4dd3-a8a7-cb4e803af17b.png",
    "https://img.xkw.com/dksih/QBM/editorImg/2025/3/5/93e99efc-5136-4ba0-bb4a-9388db4122ed.png",
]

[[stemlist]]
origin = "23-24八年级下·浙江绍兴·阶段练习"
stem = "14. 阴雨天时，空气潮湿，能见度低，路面湿滑，为保证行人的安全，需在天桥入口处设置警示灯。图甲是某同学为此设计的部分模拟电路，电磁铁及触点1固定不动，衔铁可在电磁铁作用下上下运动，带动铜棒OF 绕O 点运动。该电路中需用到阻值随空气湿度变化的湿敏电阻，将湿敏电阻接在电路中（图中未画出），闭合开关S，当空气湿度小于设定值时，警示灯随湿度变化而自动调整亮度；当空气湿度增大到设定值时，警示灯能不断闪烁，图乙是可供选择的两种湿敏电阻的阻值随湿度变化的关系图像。忽略电磁铁线圈电阻，灯泡阻值不变，以下说法正确的是（　　）A．应选R1作为该电路的湿敏电阻B．在M、N、Q三处位置中，湿敏电阻应安装在Q 处C．小于设定值时，湿度越小警示灯越亮D．向左移动滑片P，可使警示灯在较小湿度下实现闪烁"
origin_from_our_bank = []
is_title = false
imgs = ["https://img.xkw.com/dksih/QBM/editorImg/2024/5/9/043fe8fe-d9c3-4c5a-a2fa-d5f873968365.png"]

[[stemlist]]
origin = "24-25八年级下·浙江杭州·期中"
stem = "15. 有三种元素X，Y，Z，已知X和Y原子的核外电子层数相同，Y和Z原子最外层电子数相同，又知三种元素最外层电子总数之和为17，而质子数之和为31，则三种元素X、Y、Z可能是（　　）A．碳，氮，磷B．氮，氧，硫C．氮，磷，氟D．钠，氧，硫"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = ""
stem = "二、填空题"
origin_from_our_bank = []
is_title = true

[[stemlist]]
origin = "24-25八年级下·浙江杭州·期中"
stem = "16. 根据化合价，写出下列物质的化学式。氧气_________，二氧化碳_________，氧化铁_________，氯化氢_________，硫酸钡_________，硝酸银_________，碳酸钙_________，氢氧化钠_________。"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "24-25八年级下·浙江杭州·期中"
stem = "17. 指出下列符号中数字“2”所表示的意义。N2：  _________ ，     2H：_________ ，Mg2+  ：_________ ，     2Al3+：_________ 。"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "24-25八年级下·浙江杭州·期中"
stem = "18. 将缝衣针的一端在磁铁的一端接触一会，它就被磁化有了磁性。将磁化后的两根缝衣针穿过按扣的两个孔，放在底座的钉尖上，就制作成了一个如图所示的小指南针。小指南针静止时恒指南北方向的原因是受到了_________ 的作用。该指南针静止后，发现其针尖指北，则针尖是小指南针的_________ （选填“N”或“S”）极。此实验中缝衣针所用的材料最好是_________   （选填“铝”“铁”或“铜”）。"
origin_from_our_bank = []
is_title = false
imgs = ["https://img.xkw.com/dksih/QBM/editorImg/2025/6/3/3c0e257f-8ba1-490f-b2b0-f72439384ecd.png"]

[[stemlist]]
origin = "24-25八年级下·浙江杭州·期中"
stem = "19. 图甲表示R原子转变为离子的过程，请分析回答下列问题：(1)由图甲可知，该转变过程的本质为_________ 。(2)由图甲可知，此时R元素的化合价为_________ 价，请写出R元素与氧元素组成的化合物的化学式_________ 。"
origin_from_our_bank = []
is_title = false
imgs = ["https://img.xkw.com/dksih/QBM/editorImg/2025/6/4/f4b7ecfd-6566-47f0-9e3a-24a02397ad6e.png"]

[[stemlist]]
origin = "13-14八年级下·浙江杭州·期中"
stem = "20. 如图所示是简易压力传感器的原理图，弹簧甲连接在A、B两绝缘板之间，B板固定，滑动变阻器R的滑片P与A板相连，并可随A板一起运动。弹簧乙下端挂有一永磁体，永磁体正下方有一电磁铁，R0为定值电阻。开关S闭合，电路接通后，电压表示数为U1，弹簧乙甲的总长度为L1；当用力F向下压弹簧甲后，电压表示数为U2，弹簧乙的总长度为L2，，则U1_____U2，L1_______L2（均选填“＞”、“＜”或“＝”）。"
origin_from_our_bank = []
is_title = false
imgs = ["https://img.xkw.com/dksih/QBM/2020/11/6/2586968498970624/2588550430064640/STEM/acf66a7acbc74062a80086cc9703e636.png"]

[[stemlist]]
origin = ""
stem = "三、解答题"
origin_from_our_bank = []
is_title = true

[[stemlist]]
origin = "21-22八年级下·浙江温州·期末"
stem = "21. 图甲为某家用电路示意图，为防止电路短路而引发火灾，小明欲将某款双金属片断路器接入该家庭电路中，图乙为断路器分别在“电路正常”和“某处短路”两种状态的示意图。（1）图甲中灯泡与插座的联接方式是___________；（2）将断路器接入图甲中M处时，应选择a、b、c中的___________两个接线柱；（3）小明将该断路器接入图甲中N处，在使用中因电灯L发生短路导致断路器断开，若用测电笔测试插座三个孔的带电情况，其中能使氖管发光的是___________。A．接地插孔             B．零线插孔                  C．火线插孔"
origin_from_our_bank = []
is_title = false
imgs = ["https://img.xkw.com/dksih/QBM/editorImg/2023/2/28/014e9050-719d-4126-8cd5-34cb2a2c4b46.png"]

[[stemlist]]
origin = ""
stem = "四、填空题"
origin_from_our_bank = []
is_title = true

[[stemlist]]
origin = "23-24八年级下·浙江温州·期中"
stem = "22. 铁摄入不足可能引起缺铁性贫血，常见症状有无力、头晕、气短等。(1)某些食物中富含铁，可以预防和治疗缺铁性贫血。如每 100克鸭血中约含有30.5 毫克的铁，这里指的“铁”_____（选填“能”或“不能”）被磁铁所吸出。(2)市场上有一种常见的补铁药物：琥珀酸亚铁（C4H4FeO4），其规格如下表所示：【药物名称】琥珀酸亚铁片剂【成分】每片含琥珀酸亚铁0.1 克及其它辅料蔗糖等。【适应症】缺铁性贫血的预防及治疗。【用法与用量】口服用于治疗： 成人一日2~4片， 儿童一日1~3片， 分次服用用于预防： 成人一日1片，孕妇一日2片， 儿童一日0.5片【用后须知】如服用过量或出现严重不良反应， 应立即就医①琥珀酸亚铁中的碳、氢元素质量之比为______。②儿童为了预防缺铁性贫血，按照使用说明书上的用法和用量来服用，一天可摄入铁多少毫克？请通过计算说明。（结果保留一位小数）_______(3)小明感到头晕、气短，认为自己得了缺铁性贫血症。作为他的同学，你的建议是：_____。"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = "24-25八年级下·浙江杭州·期中"
stem = "23. 元素周期表是科学学习和研究的重要工具，下表是元素周期表的一部分，请回答有关问题。(1)元素在周期表中的分布是有规律的，表中①②③④所代表的四种元素中，属于非金属元素的是________（填序号）。(2)随着新元素的不断发现，元素周期表还将逐渐完善。科学家用大量高速钙原子轰击锫原子，形成了117号元素的原子，该元素原子核中一定含有117个_________，该过程属于_________（填“物理”或“化学”或“既不是化学也不是物理”）变化。(3)在元素周期表中，②号元素和④号元素属于同一__________填“周期”或“族”），故两种元素的_____________（填“物理”或“化学”）性质相似。"
origin_from_our_bank = []
is_title = false
imgs = ["https://img.xkw.com/dksih/QBM/editorImg/2025/6/3/25b8f197-2afc-4131-95f1-e08922b58a5f.png"]

[[stemlist]]
origin = ""
stem = "五、解答题"
origin_from_our_bank = []
is_title = true

[[stemlist]]
origin = "24-25八年级下·浙江杭州·期中"
stem = "24. 为了了解原子结构的奥秘，人类经历了漫长的探索过程。英国科学家卢瑟福为原子结构模型的建立作出了巨大贡献，他于1911年进行了著名的α粒子轰击金箔实验，为建立现代原子理论打下了基础。在实验中，①大部分α粒子直线穿过金属箔；②少部分α粒子有偏转；③极少数α粒子有较大角度的偏转，甚至被弹回。这就是著名的α粒子散射实验（如图所示），请根据所学内容进行回答。(1)本实验中的放射性物质放出的α粒子带_________（填“正”或“负”）电荷；(2)大部分α粒子直线穿过金属箔而不改变原来的方向，是因为_________非常小，且原子内部有很大空间；(3)少部分α粒子有偏转是因为原子核带正电，α粒子途经原子核附近时，受到了_________（填“引力”或“斥力”）；(4)统计不同偏转角度的α粒子数量，符合实验现象的图像是         。A．B．C．D．"
origin_from_our_bank = []
is_title = false
imgs = [
    "https://img.xkw.com/dksih/QBM/editorImg/2025/6/4/abf256bf-8400-4acb-ad0c-3afee28431bd.png",
    "https://img.xkw.com/dksih/QBM/editorImg/2025/6/4/4d2217b1-aa6d-4d7d-85ff-7ca516727423.png",
    "https://img.xkw.com/dksih/QBM/editorImg/2025/6/4/fb7b8ad8-b614-4a4d-8da7-04f86076f14f.png",
    "https://img.xkw.com/dksih/QBM/editorImg/2025/6/4/3d4fd436-0769-42fb-8498-e1b46bcfe8cd.png",
    "https://img.xkw.com/dksih/QBM/editorImg/2025/6/4/781b90e5-6029-473d-9cf7-e74092d2c09a.png",
]

[[stemlist]]
origin = ""
stem = "六、探究题"
origin_from_our_bank = []
is_title = true

[[stemlist]]
origin = "2021八年级下·浙江·专题练习"
stem = "25. 科学兴趣小组做了一个有趣的纸盒实验：在水平桌面的右端放有一个封闭纸盒，一辆绑有磁铁的小车从斜面上静止下滑后在水平桌面上向右运动。在靠近纸盒的过程中小车的速度越来越小，最后停在了A位置。如图所示：小组同学对这一现象展开了讨论：（1）小明认为小车的速度减小除了受到了摩擦力的作用外，可能还受到纸盒的影响。为了验证他的猜想，小明应该如何设置实验？___________（2）小明通过实验发现，纸盒能使小车的速度减小得更快。那纸盒里有什么呢？小芳提出了以下假设：假设1：纸盒中有铁块。       假设2：纸盒中有磁体。 假设3：纸盒中有闭合的线圈。小强根据已学的知识否认了___________。（3）小强打开纸盒，发现里面是一个闭合的线圈。为什么闭合的线圈会使小车的速度减小得更快？请对这一现象作出合理的解释：___________。"
origin_from_our_bank = []
is_title = false
imgs = ["https://img.xkw.com/dksih/QBM/2021/6/20/2747152863395840/2747286940426240/STEM/926d56fd-ce45-4417-bef7-d6d911b1e2cd.png"]

[[stemlist]]
origin = "24-25八年级下·浙江杭州·期中"
stem = "26. 为探究电磁铁的磁性强弱与哪些因素有关，小丽同学作出以下猜想。猜想①：通过电磁铁的电流越大，它的磁性越强。猜想②：外形相同的电磁铁，线圈的匝数越多，它的磁性越强。为了检验上述猜想是否正确，小科所在实验小组通过交流合作设计了以下实验方案：用漆包线（表面涂有绝缘漆的导线）在大铁钉上绕若干圈，制成简单的电磁铁。图A、B、C为实验中观察到的三种情况。根据小科的猜想和实验，回答下列问题。(1)小组同学通过观察_________ 的不同，来判断电磁铁磁性强弱；(2)通过比较图_________ 两种情况，可以验证猜想①是正确的；(3)通过比较图C中甲、乙两电磁铁对应的实验现象，可得到的结论是_________ ；(4)检查电路连接完好，小科闭合开关后发现图C中甲、乙两个铁钉都不能吸引大头针，她下一步的操作是          （填字母）。A．增大电源电压B．重新绕制电磁铁C．向右移动滑动变阻器滑片D．向左移动滑动变阻器滑片"
origin_from_our_bank = []
is_title = false
imgs = ["https://img.xkw.com/dksih/QBM/editorImg/2025/6/4/7ac9783f-a8c8-4fda-8049-e1f53d8836f5.png"]

[[stemlist]]
origin = ""
stem = "七、填空题"
origin_from_our_bank = []
is_title = true

[[stemlist]]
origin = "24-25八年级下·浙江杭州·期中"
stem = "27. 某兴趣小组在研究扬声器结构时，发现扬声器中有一个环形磁体，于是几位同学将四个完全相同的环形磁铁a、b、c、d套在塑料支架的光滑杆上，如图所示。静止时磁铁a、b、c悬浮在空中，d压在塑料支架底板上。若每个磁铁受到的重力均为G，磁铁a的上表面是N极。(1)磁铁b的上表面是_________极；(2)磁铁b受到磁铁c的斥力大小是_________；(3)磁铁d对底板的压力是_________；(4)若光滑杆足够长，在磁体a的上方再放上一个完全相同的磁体e（a、e间也相互排斥），则相邻两个磁体间的距离Lab_________Lae（填“大于”“等于”或“小于”）。"
origin_from_our_bank = []
is_title = false
imgs = ["https://img.xkw.com/dksih/QBM/editorImg/2025/6/3/1557cc63-4588-42eb-93a0-5ea4d4c27d95.png"]

[[stemlist]]
origin = ""
stem = "八、解答题"
origin_from_our_bank = []
is_title = true

[[stemlist]]
origin = "23-24八年级下·浙江·期中"
stem = "28. 如图是一种带漏电保护的插线板，若检测到火线和零线之间电流差达到或超过30mA 时，即刻切断电路，起到保护作用。（1）下图是插线板内部电路图，请将开关和三孔插座连入电路，要求开关同时控制指示灯和插座，指示灯和插座互不影响（指示灯能承受的电压较小，需串联一个电阻分压，图中已将其串联，●圆点是接线点）。（2）图中虚线框内为漏电保护器，假设人电阻约 2kΩ，人不小心碰触到插线板内的火线触电，计算说明该型号的漏电保护器能否起保护作用?"
origin_from_our_bank = []
is_title = false
imgs = [
    "https://img.xkw.com/dksih/QBM/editorImg/2024/5/17/0912f07e-0492-4976-91c3-9ed010e50413.png",
    "https://img.xkw.com/dksih/QBM/editorImg/2024/5/17/327b1320-67ed-4ead-bbba-e893f788948b.png",
]

[[stemlist]]
origin = ""
stem = "九、填空题"
origin_from_our_bank = []
is_title = true

[[stemlist]]
origin = "24-25八年级下·浙江杭州·期中"
stem = "29. 从原子论到分子学说，原子—分子论的创立，奠定了近代化学的基础，阅读下列材料回答问题：材料一：1803年，道尔顿提出原子论，认为所有物质都是由原子构成的。单质由原子直接构成，同种原子相互排斥不能结合；化合物由“复杂原子”构成，“复杂原子”由不同原子按一定整数比例简单构成。材料二：1811年，阿伏伽德罗引入新的概念——分子，提出了分子学说。对于化合物而言，分子相当于道尔顿所谓的“复杂原子”；对于单质而言，同种原子可以结合成单质原子。(1)完成下列表格中的空格部分：物质甲烷氯气五氧化二磷氦气构成物质的微粒 （写微粒符号）CH4Cl2P2O5_________(2)表中微粒中符合道尔顿“复杂原子”的是_________（写化学式）。(3)对于材料一中加点文字部分的观点有同学持反对态度，请选用（1）表中的物质，谈谈你对这句话的看法：_________。"
origin_from_our_bank = []
is_title = false

[[stemlist]]
origin = ""
stem = "十、探究题"
origin_from_our_bank = []
is_title = true

[[stemlist]]
origin = "23-24八年级下·浙江宁波·期末"
stem = "30. 以下是小江项目化学习小组设计的自动折叠伞控制系统。【项目名称】设计自动折叠伞控制系统【项目背景】同学们很喜欢到户外的学习园地中（如图甲）讨论问题。遇到下雨时，巨大的折叠伞打开操作困难。【项目要求】当空气相对湿度达到一定程度时，工作电路中的电动机M转动，折叠伞展开。【项目设计】根据要求设计如图乙的电路图。【器材选择】电磁继电器（线圈电阻不计，当通过电磁继电器的电流达到0.03安时，衔铁被吸下）、控制电压为6伏、滑动变阻器规格为“1安200欧”、灵敏电流表、电动机M、湿敏电阻、开关、导线等。(1)要满足上述项目要求，他们应该选择的湿敏电阻是下表中______（选填字母）；空气相对湿度/%102030405060708090100湿敏电阻A/Ω92908680725642302013湿敏电阻B/Ω13203042567280869092(2)【项目调试】利用上述选择的器材，组装好电路后开始测试。将滑动变阻器的滑片移至阻值最大处时，闭合开关S1，折叠伞不展开。若要使折叠伞在空气相对湿度达到80%时打开，则需要将滑动变阻器滑片P移至到阻值多大处？______（请通过计算说明）【项目评价及反思】评价指标合格待改进指标一伞可以自动展开伞不能自动展开指标二开伞时的湿度可多档调节开伞时的湿度不可调节(3)根据指标二，该装置被评为合格，请你结合上述信息和所学知识解释原因。______"
origin_from_our_bank = []
is_title = false
imgs = [
    "https://img.xkw.com/dksih/QBM/2024/7/26/3548478060290048/3564443248230400/STEM/c4b00a22f2db4729b35c0149dbc444e1.png",
    "https://staticzujuan.xkw.com/quesimg/Upload/formula/9fd5f9ecb870fedb5b9a608d9ca2f911.svg",
    "https://staticzujuan.xkw.com/quesimg/Upload/formula/9efc18a5bb2e53586331b2a58538a48b.svg",
    "https://staticzujuan.xkw.com/quesimg/Upload/formula/19f20f21a9d50b61dac519a3ddab539d.svg",
]

[[stemlist]]
origin = ""
stem = "十一、解答题"
origin_from_our_bank = []
is_title = true

[[stemlist]]
origin = "2022·浙江杭州·二模"
stem = "31. 随着家庭电气化程度越来越高，用电安全是一个十分突出的问题，下表提供了一组人体电阻的数据。如图所示，用电器R（阻值为44欧），电路中还有熔断电流为8A的保险丝。则：测量项目手和手之间电阻手与脚之间电阻手与塑料鞋底之间电阻完全干燥时200千欧300千欧8000千欧出汗或潮湿时1千欧1千欧10千欧（1）一个全身潮湿的人，赤脚站在地上，由于不小心，手接触火线，发生触电事故，则通过人体的电流是___________A，通过计算分析此时保险丝是否熔断___________；（2）当发现有人触电时，应该第一时间___________，在触电者未脱离电源前，严禁直接用手去触及伤员；（3）为用电安全，有的电热水器安装了防电墙。防电墙技术就是在电热水器内部形成永久性电阻，从而降低异常情况下经过人体的电流值。经过防电墙处理后，发生异常情况时，人体承受的电压约10V，如图所示，这就保证了人体安全。若人体的最大电组约为20兆欧，求防电墙的电阻大约是多少？___________"
origin_from_our_bank = []
is_title = false
imgs = ["https://img.xkw.com/dksih/QBM/editorImg/2022/7/28/39181580-08ba-4725-987a-172e697319d6.png"]

[[stemlist]]
origin = "24-25八年级下·浙江杭州·期中"
stem = "32. 硝酸铵是农业生产中广泛使用的化肥，根据硝酸铵化学式（NH4NO3）回答：(1)硝酸铵中氮元素的化合价分别为_________，_________；(2)500g 硝酸铵中含氮元素_________g；(3)多少克硝酸铵中所含氮元素的质量和120g尿素[ CO（NH2）2]中所含氮元素的质量相等？(4)已知所购买的化肥中硝酸铵的含量为90%，则该化肥中氮元素的含量为多少？"
origin_from_our_bank = []
is_title = false
